PERSONAL_INCOME_TAX_RATE = 0.18
MILITARY_TAX_RATE = 0.015
SINGLE_CONTRIBUTION_RATE = 0.22

MINIMUM_SALARY = 8000
SINGLE_CONTRIBUTION_BASE_MIN = MINIMUM_SALARY
SINGLE_CONTRIBUTION_BASE_MAX = MINIMUM_SALARY * 15
